# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

strategy:
  matrix:
    jdk8_linux:
      imageName: "ubuntu-latest"
      jdk_version: "1.8"
    jdk8_windows:
      imageName: "vs2017-win2016"
      jdk_version: "1.8"
  maxParallel: 2

pool:
  vmImage: $(imageName)

steps:
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: $(jdk_version)
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'build'
